spring:
  application:
    name: hddplus-concert
  datasource:
    url: jdbc:h2:mem:concertdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
springdoc:
  api-docs:
    enabled: true  # API ?? ?? ?? (??? true)
  swagger-ui:
    path: /swagger-ui.html # Swagger UI? ???? ?? (??? /swagger-ui/index.html)